"""Build the slim runtime data bundle for the hosted API and push it to the `deploy-data` branch.

main stays code-only (data/ is git-ignored); the Docker build on Render downloads this branch as a tarball
into /app/data. Re-run after train.py / replay.py / demo.py, or to refresh the snapshot:

    python tools/deploy/publish_data.py            # build + push
    python tools/deploy/publish_data.py --no-push  # build only (build/deploy-data)
"""
import glob, json, os, shutil, subprocess, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "build", "deploy-data")
BRANCH = "deploy-data"
NLAT, NLON = 129, 135

FILES = [
    "boundaries/districts.json", "boundaries/districts_simplified.geojson", "boundaries/cell_district.npy",
    "normals_1991_2020.npz", "rsmc/rsmc_tracks.csv",
    "models/regime_history.json", *[f"models/lead{l}.pkl" for l in range(1, 6)], *[f"models/verification_lead{l}.json" for l in range(1, 6)],
    "products/latest.json", "products/replay_index.json",
]
TREES = ["products/replay", "products/demo"]


def copy(rel):
    src, dst = os.path.join(DATA, rel), os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)


def build():
    if os.path.exists(OUT):
        shutil.rmtree(OUT, onerror=lambda f, p, e: (os.chmod(p, 0o700), f(p)))
    os.makedirs(OUT)
    for rel in FILES: copy(rel)
    for t in TREES: shutil.copytree(os.path.join(DATA, t), os.path.join(OUT, t))
    # recent IMD real-time grids (regime needs the last 15 days) and the last few GFS runs
    for sub, n in (("imd_rt", 20), ("gfs", 5)):
        for f in sorted(glob.glob(os.path.join(DATA, sub, "*")))[-n:]: copy(os.path.relpath(f, DATA))
    # land mask (replaces the 25 MB IMD 2020 year file) for the engine and the API
    g = np.fromfile(os.path.join(DATA, "imd_yearly", "2020.grd"), dtype="<f4").reshape(-1, NLAT, NLON)[200]
    land = g > -998
    np.save(os.path.join(OUT, "land_mask.npy"), land)
    runs = []
    for i in range(NLAT):
        s = -1
        for j in range(NLON + 1):
            on = j < NLON and land[i, j]
            if on and s < 0: s = j
            if not on and s >= 0: runs.append([i, s, j - 1]); s = -1
    json.dump({"lat0": 6.5, "lon0": 66.5, "step": 0.25, "runs": runs, "source": "IMD 0.25° gridded rainfall land mask"},
              open(os.path.join(OUT, "products", "landmask.json"), "w"))
    open(os.path.join(OUT, "README.md"), "w").write(
        "# VARSHA runtime data\n\nGenerated by `tools/deploy/publish_data.py` on the main branch. "
        "Official sources only: IMD Pune gridded rainfall, IMD RSMC New Delhi best tracks, Survey of India districts, NOAA GFS.\n")
    size = sum(os.path.getsize(f) for f in glob.glob(os.path.join(OUT, "**", "*"), recursive=True) if os.path.isfile(f))
    print(f"bundle: {OUT} ({size / 1e6:.1f} MB)")


def push():
    remote = subprocess.check_output(["git", "-C", ROOT, "remote", "get-url", "origin"], text=True).strip()
    run = lambda *a: subprocess.check_call(["git", "-C", OUT, *a])
    run("init", "-q"); run("checkout", "-q", "-b", BRANCH); run("add", "-A")
    run("commit", "-q", "-m", "VARSHA runtime data snapshot\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>")
    run("push", "-f", remote, f"{BRANCH}:{BRANCH}")
    print(f"pushed {BRANCH} to {remote}")


if __name__ == "__main__":
    build()
    if "--no-push" not in sys.argv: push()
